In [1]:
import numpy as np
import gym
import random 
import time
from IPython.display import clear_output

#### Create Environment object to query for info, sample states and actions, retrive rewards and have agent navigate frozen lake

In [2]:
env = gym.make("FrozenLake-v0")

#### Constructing Q-Table

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### Initializing Q-Learning Parameters

In [4]:
num_episodes = 10000
max_steps_per_episode = 100
learning_rate = 0.1
discount_rate = 0.99
exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [5]:
rewards_for_all_episodes =[]

#### Q-Learning Algorithm

In [6]:
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_for_current_episode = 0
    
    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        
        #Take new action
        new_state, reward, done, info = env.step(action)
        
        #Update the q-value table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + learning_rate*(reward + discount_rate*np.max(q_table[new_state, :]))
        
        #Transition to new state
        state = new_state
        rewards_for_current_episode += reward
        
        if done == True:
            break
        
    #Exploration of rate of decay
    exploration_rate= min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    
    rewards_for_all_episodes.append(rewards_for_current_episode)

#### Calculate and print the average reward per thousand episodes

In [7]:
rewards_per_thousand_episodes = np.split(np.array(rewards_for_all_episodes), num_episodes/1000)
count = 1000
print("******** Average reward per thousand episodes ********\n")
for r in rewards_per_thousand_episodes:
    print(count, " : ", str(sum(r/1000)))
    count += 1000

******** Average reward per thousand episodes ********

1000  :  0.04200000000000003
2000  :  0.22700000000000017
3000  :  0.43200000000000033
4000  :  0.5540000000000004
5000  :  0.6370000000000005
6000  :  0.6450000000000005
7000  :  0.6790000000000005
8000  :  0.6740000000000005
9000  :  0.6580000000000005
10000  :  0.7050000000000005


#### Print the Q-Table

In [8]:
print("\n\n ***Q-Table***\n")
print(q_table)



 ***Q-Table***

[[0.58207745 0.52892997 0.53397933 0.52471976]
 [0.29909646 0.41132885 0.29221347 0.52769968]
 [0.41000242 0.4182196  0.40264636 0.48393931]
 [0.22855355 0.27613655 0.28423659 0.45922562]
 [0.59750313 0.43441191 0.47522545 0.18591514]
 [0.         0.         0.         0.        ]
 [0.15563698 0.1783488  0.26473376 0.03424756]
 [0.         0.         0.         0.        ]
 [0.456476   0.49509772 0.51103213 0.62376755]
 [0.39941202 0.64100386 0.37642438 0.33062478]
 [0.57228264 0.45080391 0.41518435 0.30434967]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.44781739 0.5931778  0.76056292 0.55818474]
 [0.72330016 0.88303681 0.73768423 0.71996868]
 [0.         0.         0.         0.        ]]


#### Watch the agent play Frozen lake by it taking it's beat actions and converging on an optimal q-value.

In [20]:
#From state according to Q-table
for episode in range(3):
    state = env.reset()
    done = False
    clear_output(wait=True)
    print("*** Episode", episode+1,"**\n\n\n\n")
    time.sleep(1)
    
    #For each time step
    for step in range(max_steps_per_episode):
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait = True)
            env.render()
            if reward == 1:
                print("***** You reached your goal! *****")
                time.sleep(3)
            else:
                print("***** You fell through the hole! *****")
                time.sleep(3)
                clear_output(wait = True)
            break
        state = new_state
        
env.close()        

  (Down)
SFFF
FHFH
FFFH
HFFG
***** You reached your goal! *****
